### ISSUE TITLE
Complete files about tweets

### ISSUE THREAD

**Issue by ines1121** [rbtkay/INGR-Twitter#63]
**Description**  
Documentation and indentation. Modify root to return tweets

**Comment by chizzel36** [comment]
@ines1121

**Comment by chizzel36** [comment]
> **Description**  
> Documentation and indentation. Modify root to return tweets
> 
> 
> Documentation Modify

**Comment by chizzel36** [comment]
Modify tweet

**Comment by chizzel36** [comment]
> Modify tweet
